services:

  world-chain:
    image: ghcr.io/worldcoin/world-chain:v2.3.0
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-reth.sh
    ports:
      - ${PORT__EXECUTION_HTTP:-8545}:8545
      - ${PORT__EXECUTION_WS:-8546}:8546
      - ${PORT__EXECUTION_P2P:-30303}:${PORT__EXECUTION_P2P:-30303}/udp
      - ${PORT__EXECUTION_P2P:-30303}:${PORT__EXECUTION_P2P:-30303}/tcp
    volumes:
        - ./envs/${NETWORK_NAME}/config:/chainconfig
        - op_reth:/data
        - ./scripts/:/scripts
        - shared:/shared
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.18.2
    restart: unless-stopped
    stop_grace_period: 5m
    command:
      - op-node
      - --l1=$L1_RPC_ENDPOINT
      - --l2=ws://world-chain:8551
      - --l2.enginekind=reth
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
      - --l2.jwt-secret=/shared/jwt.txt
      - --l1.trustrpc
      - --l1.rpckind=$L1_RPC_TYPE
      - --l1.beacon=$L1_BEACON_RPC_ENDPOINT
      - --metrics.enabled
      - --metrics.addr=0.0.0.0
      - --metrics.port=7300
      - --p2p.listen.tcp=${PORT__CONSENSUS_P2P:-9222}
      - --syncmode=execution-layer
      - --network=$NETWORK_NAME
      - --p2p.useragent=worldchain
    env_file:
      - .env
    volumes:
      - ./envs/${NETWORK_NAME}/config:/chainconfig
      - ./scripts/:/scripts
      - shared:/shared
    ports:
      - ${PORT__CONSENSUS_P2P:-9222}:${PORT__CONSENSUS_P2P:-9222}/udp
      - ${PORT__CONSENSUS_P2P:-9222}:${PORT__CONSENSUS_P2P:-9222}/tcp
      - ${PORT__CONSENSUS_HTTP:-9545}:9545
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus:v3.10.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:12.3
    restart: unless-stopped
    env_file:
      -  ./envs/common/grafana.env
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - ${PORT__GRAFANA:-3000}:3000

volumes:
  prometheus_data:
  grafana_data:
  shared:
  op_reth:
